### ISSUE TITLE
Wrtiting up appconfiguration.json file not working in docker container

### ISSUE THREAD

**Issue by gillmk** [IBM/appconfiguration-go-sdk#7]
If I run build a docker container which is trying to create AppConfiguration client, it fails to write the file and panics. 

Library should not write any files in the file system as file system may be read only.

```
time="2021-05-19T15:29:11Z" level=error msg="Error while writing to a file open ./appconfiguration.json: permission denied"
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/IBM/appconfiguration-go-sdk/lib/internal/models.getTypeCastedValue(...)
        /Users/manvindergill/go/workspaces/security-service-workspace/pkg/mod/github.com/!i!b!m/appconfiguration-go-sdk@v1.2.0/lib/internal/models/ConfigurationType.go:31
github.com/IBM/appconfiguration-go-sdk/lib/internal/models.(*Feature).GetCurrentValue(0xc0002ef4a0, 0x1a25dd0, 0x3, 0xc0002ef470, 0xc0002ef5a8, 0x0)
        /Users/manvindergill/go/workspaces/security-service-workspace/pkg/mod/github.com/!i!b!m/appconfiguration-go-sdk@v1.2.0/lib/internal/models/Feature.go:66 +0x248
main.createAppConfig()
        /Users/manvindergill/go/workspaces/security-service-workspace/iam-rest-server/cmd/iam-rest-server/main.go:427 +0x305
main.main()
        /Users/manvindergill/go/workspaces/security-service-workspace/iam-rest-server/cmd/iam-rest-server/main.go:76 +0x5f
```

**Comment by srikanthkm** [comment]
The issue is being investigated and will update the findings here at the earliest.

**Comment by ibm-cloud-appconfiguration** [comment]
The SDK is now updated to use the in-memory implementation instead of the File cache for its operation. 

Go SDK v0.1.1 contains the in-memory cache implementation instead of using a File as a cache, which required write permissions to be provided.
